project_name: "user_api"
md5_salt: "test"
captcha_expire_sec: 30
mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123123"
  database: "mychat"

logger:
  filename: "logs/test.log"
  max_size: 1
  max_backups: 5
  max_age: 1
  compress: false

jwt:
  signing_key: "test"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  database: 0
