project_name: "chat_srv"
md5_salt: "test"
mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "123123"
  database: "mychat"

logger:
  filename: "logs/test.log"
  max_size: 1
  max_backups: 5
  max_age: 1
  compress: false

consul:
  host: "127.0.0.1"
  port: 8500
  tags: ["test","chat_srv"]
